# Generated by Django 5.2.5 on 2025-08-10 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=100)),
                ("publication_year", models.PositiveIntegerField()),
                ("available_copies", models.PositiveIntegerField(default=1)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title", "author"],
                "indexes": [
                    models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
                    models.Index(
                        fields=["author"], name="books_book_author_b941fe_idx"
                    ),
                    models.Index(fields=["genre"], name="books_book_genre_4a7cdf_idx"),
                ],
            },
        ),
    ]
