# Generated by Django 5.2.5 on 2025-08-08 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=200)),
                ('author', models.CharField(help_text='Book author', max_length=200)),
                ('genre', models.CharField(blank=True, help_text='Book genre for categorization', max_length=100, null=True)),
                ('total_copies', models.PositiveIntegerField(default=1, help_text='Total number of copies in the library', validators=[django.core.validators.MinValueValidator(1)])),
                ('available_copies', models.PositiveIntegerField(default=1, help_text='Number of copies currently available for borrowing', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the book was added to the system')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='books_title_7a737c_idx'), models.Index(fields=['author'], name='books_author_1c43f5_idx'), models.Index(fields=['genre'], name='books_genre_d6e4af_idx')],
            },
        ),
    ]
