services:
  db:
    image: postgres:latest
    container_name: lms-postgres
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lms_user -d lms"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    container_name: lms-django
    environment:
      - DB_NAME=lms
      - DB_USER=lms_user
      - DB_PASSWORD=lms_password
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
