version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://lms_user:lms_password@db:5432/lms
  db:
    image: postgres:latest
    container_name: lms-postgres
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:alpine
    container_name: lms-redis
    ports:
      - "6380:6379"
  celery:
    build: .
    command: celery -A lms worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data: